---
language: ruby
cache: bundler

branches:
  except:
    - /^prod\//
    - /^stage\//

addons:
  postgresql: "9.6.3"

before_install:
  - gem update bundler

before_script:
  - api/bin/bundle install

script:
  - api/bin/rails db:drop db:create db:migrate --trace
  - api/bin/rspec
