---
language: ruby
cache: bundler
gemfile:
  - api/Gemfile

branches:
  except:
    - /^prod\//
    - /^stage\//

addons:
  postgresql: "10.3.0"

before_install:
  - gem update bundler

before_script:
  - api/bin/bundle install

script:
  - api/bin/rails db:drop db:create db:migrate --trace
  - api/bin/rspec
