default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: reddit_clone_development

test: &test
  <<: *default
  database: reddit_clone_test

production:
  <<: *default
  database: reddit_clone_production

