# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75bc4d37e4ede3f9ab3ffaaa97f2cb230dc5fd6704ffec1ec4adf167450b46a313302880999ea6c64632a495fb00109136ff62f68fb0a4d4b91add8e58a35d65

test:
  secret_key_base: ccf019b63284aa6f768197e7a4e8c6a221204fdfcfba97b8f8502599529a8a789fb5190c2a53209882aac6a6cd78aee233ff904ac48971bbac5481b94855112d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
